ALTER TABLE students
ADD COLUMN otp VARCHAR(10),
ADD COLUMN otp_created_at TIMESTAMP,
ADD COLUMN otp_expires_at TIMESTAMP,
ADD COLUMN is_verify BOOLEAN DEFAULT false,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
